// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 14.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AppAssets {
  static const String package = 'keepup';

  static const String ic_launcher_png = 'assets/app_icons/ic_launcher.png';

  static const String ic_launcher_background_png = 'assets/app_icons/ic_launcher_background.png';

  static const String ic_launcher_foreground_png = 'assets/app_icons/ic_launcher_foreground.png';

  static const String ic_contacts_svg = 'assets/icons/ic_contacts.svg';

  static const String ic_facebook_png = 'assets/icons/ic_facebook.png';

  static const String ic_filter_svg = 'assets/icons/ic_filter.svg';

  static const String ic_google_png = 'assets/icons/ic_google.png';

  static const String ic_groups_svg = 'assets/icons/ic_groups.svg';

  static const String ic_linkin_png = 'assets/icons/ic_linkin.png';

  static const String ic_next_svg = 'assets/icons/ic_next.svg';

  static const String ic_soon_svg = 'assets/icons/ic_soon.svg';

  static const String ic_today_svg = 'assets/icons/ic_today.svg';

  static const String ic_whatsapp_svg = 'assets/icons/ic_whatsapp.svg';

  static const String img_logo_png = 'assets/images/img_logo.png';
}
