name: keepup
description: KeepUp

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Check permission
  permission_handler: ^11.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Images
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

  # Dependency injection / router navigator / multi-languages / dialog
  get: ^4.6.5

  # Bloc/State/Event
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Shared pref
  hive: ^2.2.3

  # Network
  retrofit: ^4.0.1

  # Caching API calls
  dio: ^5.0.0
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1

  rxdart: ^0.27.7

  # Drift - Local Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.0.0
  path: ^1.8.0

  # Check status connection internet
  connectivity_plus: ^4.0.2

  # Immutable models
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # process when press button back system [Android Only]
  back_system:
    git:
      url: https://gitlab.com/thangnguyenvu1991/back_system.git

  # Depend on referenced packages
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0

  # Display in App Toast a customized progress widgets based on percentage, can be Circular or Linear
  percent_indicator: ^4.2.3

  # Vectorized Icons Support
  flutter_svg: ^2.0.7

  # animation load network image
  octo_image: ^1.0.2

  # Intl
  intl: ^0.18.0

  # Launch url
  url_launcher: ^6.1.14

  flutter_widget_from_html: ^0.10.2

  # Images
  file_picker: ^6.1.1
  thumbnailer: ^2.2.0

  # Slidable widget
  flutter_slidable: ^3.0.1

  # Supabase
  supabase_flutter: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.3

  # Auto create launch icon
  flutter_launcher_icons:
    git:
      url: https://github.com/knyghtryda/flutter_launcher_icons
      ref: scaling

  # Assets generation
  assets_gen: ^1.5.0

  # for Auto Generator
  build_runner: ^2.4.6
  freezed: ^2.4.1

  # for Hive
  hive_generator: ^2.0.1

  # for Drift
  drift_dev: ^2.14.0

  # for Retrofit
  retrofit_generator: ^7.0.2

  # Json
  json_serializable: ^6.7.1

  # Change package
  change_app_package_name: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_icons/
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-Regular.ttf
          weight: 400


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
